services:
  - type: web
    plan: free
    name: pixagram
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn pixagram.asgi:application -k uvicorn.workers.UvicornWorker"